workspace(
    name = "bazel-yocto",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "bazel_toolchains_yocto",
    sha256 = "cd2683c2252c3113719f49a7a3c15c3c90d0bdfa37a1e254db243fda308ca727",
    strip_prefix = "bazel-toolchains-yocto-0.0.4",
    url = "https://github.com/pziggo/bazel-toolchains-yocto/archive/refs/tags/v0.0.4.tar.gz",
)

load("@bazel_toolchains_yocto//yocto:repositories.bzl", "bazel_toolchains_yocto_dependencies")

bazel_toolchains_yocto_dependencies()

load("@bazel_toolchains_yocto//yocto:defs.bzl", "http_yocto_toolchain_archive", "http_yocto_toolchain_file", "local_yocto_toolchain")

http_yocto_toolchain_file(
    name = "cortexa57",
    build_file = "@//:BUILD.cortexa57",
    environment_setup = "environment-setup-cortexa57-poky-linux",
    sha256 = "456eb2820f1ec975f01e30c6df2021ca7030080fd299767a96757e63da7cb488",
    urls = [
        "https://downloads.yoctoproject.org/releases/yocto/yocto-4.1.2/toolchain/x86_64/poky-glibc-x86_64-core-image-sato-cortexa57-qemuarm64-toolchain-4.1.2.sh",
    ],
)

http_archive(
    name = "rules_proto",
    sha256 = "dc3fb206a2cb3441b485eb1e423165b231235a1ea9b031b4433cf7bc1fa460dd",
    strip_prefix = "rules_proto-5.3.0-21.7",
    urls = [
        "https://github.com/bazelbuild/rules_proto/archive/refs/tags/5.3.0-21.7.tar.gz",
    ],
)
load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()
